### ISSUE TITLE
Setting base_url is not used

### ISSUE THREAD

**Issue by pacnos** [zostera/django-bootstrap4#105]
I tried to change the used bootstrap4 version. So I added to following dict to the settings.py:

`BOOTSTRAP4 = {
    # The Bootstrap base URL
    'base_url': '//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/',
}`

But the tag {% bootstrap_css %} still includes version 4.0.0:

`<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">`

**Comment by dyve** [comment]
Do you have a `css_url` defined in settings?

**Comment by pacnos** [comment]
No, the `css_url` is not set in my settings file. As I understod the documentation, if I didn't set a `css_url` the url will be build from the `base_url`. Is this correct?

**Comment by dyve** [comment]
Yes, that's why I asked. I'll investigate.

**Comment by dyve** [comment]
I've confirmed this is due to a change in the defaults. The CDN version of BS4 used to be provided by a `base_url`. In order to accommodate crossorigin/integrity, the defaults are now in a `css_url` and `javascript_url`.

This will require a fix, and the fix may require some discussion.

Workaround for now: explicitly set `css_url` to `None` in your settings, and your `base_url` will work.

**Comment by dyve** [comment]
Suggestion. Let's get rid of `base_url` as a magic way to include stuff, and just have an explicit `javascript_url` and `css_url` that default to the CDN. This would be a breaking change.

**Comment by dyve** [comment]
@pacnos Would you that be an acceptable direction for you?

**Comment by pacnos** [comment]
@dyve Sounds like a good and simple solution ....
